
-- CREATE database and schema
CREATE OR REPLACE DATABASE REAL_ESTATE_DB;
CREATE OR REPLACE SCHEMA REAL_ESTATE_DB.PUBLIC;

-- Small warehouse for minimal credits
CREATE WAREHOUSE IF NOT EXISTS REAL_ESTATE_WH
  WAREHOUSE_SIZE = 'X-SMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

USE WAREHOUSE REAL_ESTATE_WH;
USE DATABASE REAL_ESTATE_DB;
USE SCHEMA REAL_ESTATE_DB.PUBLIC;

-- File format
CREATE OR REPLACE FILE FORMAT REAL_ESTATE_DB.PUBLIC.CSV_FORMAT
TYPE = 'CSV'
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
SKIP_HEADER = 1
NULL_IF = ('NULL','');

-- Stage
CREATE OR REPLACE STAGE REAL_ESTATE_DB.PUBLIC.REAL_ESTATE_STAGE
FILE_FORMAT = REAL_ESTATE_DB.PUBLIC.CSV_FORMAT;

-- Tables (abridged types; ajuste según necesidad)
CREATE OR REPLACE TABLE REAL_ESTATE_DB.PUBLIC.locations (
    location_id INT,
    city VARCHAR(100),
    state VARCHAR(10),
    county VARCHAR(100),
    zipcode VARCHAR(10),
    msa_code VARCHAR(20),
    population INT,
    median_income INT,
    median_age FLOAT,
    avg_household_size FLOAT,
    unemployment_rate FLOAT,
    poverty_rate FLOAT,
    gdp_per_capita INT,
    avg_commute_time FLOAT,
    school_count INT,
    hospital_count INT,
    parks_count INT,
    crime_index FLOAT,
    walk_score INT,
    transit_score INT,
    bike_score INT,
    flood_risk_score FLOAT,
    earthquake_risk FLOAT,
    wildfire_risk FLOAT,
    zoning_type VARCHAR(50),
    avg_listing_price INT,
    avg_sale_price INT,
    price_per_sqft FLOAT,
    housing_stock INT,
    vacancy_rate FLOAT,
    rent_to_income_ratio FLOAT,
    property_tax_rate FLOAT,
    sales_volume_12m INT,
    new_construction_permits INT,
    historical_growth_rate FLOAT,
    timezone VARCHAR(50),
    daylight_savings BOOLEAN,
    coord_lat FLOAT,
    coord_lon FLOAT,
    census_tract VARCHAR(50),
    neighborhood_rating INT,
    population_density INT
);

CREATE OR REPLACE TABLE REAL_ESTATE_DB.PUBLIC.agents (
    agent_id INT,
    agent_uid VARCHAR(20),
    first_name VARCHAR(50),
    last_name VARCHAR(50),
    agency VARCHAR(100),
    phone VARCHAR(30),
    email VARCHAR(200),
    license_number VARCHAR(50),
    license_state VARCHAR(10),
    years_experience INT,
    transaction_count INT,
    avg_sale_price INT,
    commission_rate FLOAT,
    office_address VARCHAR(200),
    office_city VARCHAR(100),
    office_state VARCHAR(20),
    office_zip VARCHAR(20),
    languages VARCHAR(100),
    specialties VARCHAR(100),
    ratings FLOAT,
    bio VARCHAR(1000),
    social_links VARCHAR(500),
    awards VARCHAR(200),
    certifications VARCHAR(200),
    active_flag BOOLEAN,
    date_joined DATE,
    last_transaction_date DATE,
    listings_current INT,
    sales_closed_12m INT,
    leads_open INT,
    avg_days_on_market INT,
    response_time_hours FLOAT,
    team_size INT,
    license_expiry DATE,
    crm_used VARCHAR(100),
    website VARCHAR(200),
    photo_url VARCHAR(400)
);

CREATE OR REPLACE TABLE REAL_ESTATE_DB.PUBLIC.owners (
    owner_id INT,
    owner_uid VARCHAR(20),
    first_name VARCHAR(50),
    middle_name VARCHAR(50),
    last_name VARCHAR(50),
    company VARCHAR(200),
    email VARCHAR(200),
    phone VARCHAR(30),
    secondary_phone VARCHAR(30),
    mailing_address VARCHAR(200),
    mailing_city VARCHAR(100),
    mailing_state VARCHAR(20),
    mailing_zipcode VARCHAR(20),
    tax_id VARCHAR(50),
    date_of_birth DATE,
    ownership_type VARCHAR(50),
    ownership_percentage FLOAT,
    primary_contact BOOLEAN,
    preferred_contact_method VARCHAR(50),
    investor_flag BOOLEAN,
    investor_type VARCHAR(100),
    notes VARCHAR(1000),
    created_at DATE,
    updated_at DATE,
    num_properties_owned INT,
    average_property_value INT,
    total_portfolio_value INT,
    last_transaction_date DATE,
    credit_score INT,
    preferred_bank VARCHAR(200),
    legal_rep VARCHAR(200),
    is_trust BOOLEAN,
    trust_name VARCHAR(200),
    entity_type VARCHAR(50),
    registration_state VARCHAR(20),
    years_as_owner INT,
    risk_profile VARCHAR(50),
    accreditation_status VARCHAR(50),
    referral_source VARCHAR(100),
    owners_since DATE,
    social_media VARCHAR(300),
    website_url VARCHAR(300)
);

CREATE OR REPLACE TABLE REAL_ESTATE_DB.PUBLIC.properties (
    property_id INT,
    property_uid VARCHAR(30),
    owner_id INT,
    location_id INT,
    address VARCHAR(300),
    city VARCHAR(100),
    state VARCHAR(20),
    zipcode VARCHAR(20),
    county VARCHAR(100),
    latitude FLOAT,
    longitude FLOAT,
    price INT,
    list_price INT,
    sale_price INT,
    bedrooms INT,
    bathrooms FLOAT,
    sqft INT,
    lot_size FLOAT,
    year_built INT,
    property_type VARCHAR(100),
    heating VARCHAR(100),
    cooling VARCHAR(100),
    parking VARCHAR(100),
    hoa_fee FLOAT,
    days_on_market INT,
    status VARCHAR(50),
    school_rating INT,
    crime_rate FLOAT,
    flood_zone BOOLEAN,
    energy_rating VARCHAR(10),
    last_renovation_date DATE,
    listing_date DATE,
    sale_date DATE,
    listing_agent_id INT,
    garage_spaces INT,
    basement BOOLEAN,
    fireplace BOOLEAN,
    pool BOOLEAN,
    roof_type VARCHAR(100),
    exterior_material VARCHAR(100),
    interior_features VARCHAR(500),
    appliances VARCHAR(500),
    flooring VARCHAR(100),
    neighborhood_rating INT,
    walk_score INT,
    transit_score INT,
    bike_score INT,
    tax_assessed_value INT
);

CREATE OR REPLACE TABLE REAL_ESTATE_DB.PUBLIC.transactions (
    transaction_id INT,
    transaction_uid VARCHAR(30),
    property_id INT,
    buyer_id INT,
    seller_id INT,
    agent_id INT,
    sale_date DATE,
    sale_price INT,
    list_price INT,
    closing_costs FLOAT,
    mortgage_amount INT,
    mortgage_rate FLOAT,
    mortgage_term_years INT,
    down_payment INT,
    financing_type VARCHAR(50),
    title_company VARCHAR(200),
    escrow_company VARCHAR(200),
    inspection_date DATE,
    appraisal_value INT,
    sale_type VARCHAR(50),
    sale_condition VARCHAR(100),
    days_on_market INT,
    commission_rate FLOAT,
    agent_split FLOAT,
    taxes_paid FLOAT,
    transfer_tax FLOAT,
    deed_type VARCHAR(100),
    recorded_date DATE,
    loan_type VARCHAR(50),
    lender_name VARCHAR(200),
    loan_status VARCHAR(100),
    buyer_agent_id INT,
    seller_agent_id INT,
    inspection_passed BOOLEAN,
    closing_date DATE,
    closing_agent VARCHAR(200),
    earnest_money FLOAT,
    contingencies VARCHAR(200),
    foreclosure_flag BOOLEAN,
    short_sale_flag BOOLEAN,
    renovation_budget FLOAT,
    after_repair_value FLOAT
);

-- End of DDL
